env: MountainCarContinuous-v0
seed: 5
featExtractor: !!python/name:__main__.NothingToDo ''
freqSave: 1000
freqTest: 10000
nbTest: 1
freqVerbose: 1000
freqOptim: 1000                                                                          # Optimisation de la politique tous les freqOptim evenements
fromFile: null
nbEpisodes: 1000000
maxLengthTrain: 200
maxLengthTest: 200